import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';
import userModel from '../models/User.js';

async function seedUsers() {
  const users = [
    await new userModel({
      fname: 'vedoor',
      lname: 'barakat',
      email: 'vedoorbbs@gmail.com',
      tag: 'vedoorbarakat',
      profilePic: '',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Alice',
      lname: 'Smith',
      email: 'alice.smith@example.com',
      tag: 'alicesmith',
      profilePic: 'alice-smith.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Bob',
      lname: 'Johnson',
      email: 'bob.johnson@example.com',
      tag: 'bobjognson',
      profilePic: 'bob-johnson.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Charlie',
      lname: 'Williams',
      email: 'charlie.williams@example.com',
      tag: 'charliewilliams',
      profilePic: 'charlie-williams.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Diana',
      lname: 'Brown',
      email: 'diana.brown@example.com',
      tag: 'dianabrown',
      profilePic: 'diana-brown.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Eve',
      lname: 'Jones',
      email: 'eve.jones@example.com',
      tag: 'evejones',
      profilePic: 'eve-jones.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Frank',
      lname: 'Garcia',
      email: 'frank.garcia@example.com',
      tag: 'frankgarcia',
      profilePic: 'frank-garcia.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Grace',
      lname: 'Martinez',
      email: 'grace.martinez@example.com',
      tag: 'gracemartinez',
      profilePic: 'grace-martinez.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Henry',
      lname: 'Hernandez',
      email: 'henry.hernandez@example.com',
      tag: 'henryhernandez',
      profilePic: 'henry-hernandez.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Ivy',
      lname: 'Lopez',
      email: 'ivy.lopez@example.com',
      tag: 'ivylopez',
      profilePic: 'ivy-lopez.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Jack',
      lname: 'Wilson',
      email: 'jack.wilson@example.com',
      tag: 'jackwilson',
      profilePic: 'jack-wilson.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Kara',
      lname: 'Anderson',
      email: 'kara.anderson@example.com',
      tag: 'karaanderson',
      profilePic: 'kara-anderson.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Leo',
      lname: 'Thomas',
      email: 'leo.thomas@example.com',
      tag: 'leothomas',
      profilePic: 'leo-thomas.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Mia',
      lname: 'Jackson',
      email: 'mia.jackson@example.com',
      tag: 'miajackson',
      profilePic: 'mia-jackson.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
    await new userModel({
      fname: 'Noah',
      lname: 'White',
      email: 'noah.white@example.com',
      tag: 'noahwhite',
      profilePic: 'noah-white.jpg',
      backgroundPic: '',
      following: [],
      followers: [],
      password: await bcrypt.hash('123123', 10),
    }),
  ];
  return users;
}

export const seedUsersAndSave = async () => {
   await seedUsers().then(async (res) => {
      res.map(async (user) => {
        await user.save()
      })
  });
};
